### ISSUE TITLE
Error: "ssh.0.public_key": this field cannot be set

### ISSUE THREAD

**Issue by robert-clarifai** [strongdm/terraform-provider-sdm#13] opened 2020-09-24 12:11 UTC
Ran into this error
```
Error: "ssh.0.public_key": this field cannot be set
```
when trying to create multiple servers with the same ssh public_key

TF snippet like this

```
resource "sdm_resource" "ssh_test_user" {
  ssh {
    name     = "node1"
    hostname = "192.168.111.111"
    username = "testuser"
    port     = 22
  }
}

resource "sdm_resource" "ssh_test_user_more" {
  ssh {
    name     = "node2"
    hostname = "192.168.111.112"
    username = sdm_resource.ssh_test_user.ssh[0].username
    port     = 22
    public_key = sdm_resource.ssh_test_user.ssh[0].public_key
  }
  ssh {
    name     = "node3"
    hostname = "192.168.111.113"
    username = sdm_resource.ssh_test_user.ssh[0].username
    port     = 22
    public_key = sdm_resource.ssh_test_user.ssh[0].public_key
  }
}

```

It works if we comment out the `public_key` but then they end up with different ssh_keys

Is it possible to create the resources with the same public key like the `sdm admin ssh clone` command?

**Comment by grioghar** [comment] 2020-10-20 19:43
Hi Robert,

My apologies this has went unseen. Is this trouble you are currently still having with your script? If so, I'd direct you to our Customer Support - support@strongdm.com - to further investigate for you. 

Doing a cursory test, I have the same issue, which makes me believe we may need to update the provider. 

Thank you!

**Comment by grioghar** [comment] 2020-10-20 20:21
Created ticket 2423 with Support.

**Comment by 200sc** [comment] 2023-01-26 15:03
Closing for staleness; in addition, this is working as intended: the public key field for the `ssh` type is read-only. To customize the key used I would recommend using the `ssh_customer_key` type.

**Closed by 200sc** 2023-01-26 15:03 UTC
