### ISSUE TITLE
Please add support for multiple roles and/or temporary access grants

### ISSUE THREAD

**Issue by nigele-stripe** [strongdm/terraform-provider-sdm#15] opened 2020-12-03 17:55 UTC
Hi,

I'm using the SDM provider v1.0.16 to provision server SSH resources for adhoc dev boxes in AWS.   Each user is assigned a devbox which creates a server SSH profile in SDM.   Ideally, we'd directly assign the server to the user via. an [account_grant](https://registry.terraform.io/providers/strongdm/sdm/latest/docs/resources/account_grant) or [role_grant](https://registry.terraform.io/providers/strongdm/sdm/latest/docs/resources/role_grant).   However this fails as SDM only allows a user to have a single role assigned (would be nice to relax this).  To work around this we leverage temporary access grants but these aren't supported via. the SDM provider.    

We're currently using a provisioner `local-exec` step that calls [grant-temporary](https://www.strongdm.com/docs/reference/admin/users/grant-temporary/) to workaround this:

```tf
// devboxes = ['user1@foo.com', 'user2@bar.com', ...]
resource "sdm_resource" "devbox" {
  for_each = var.devboxes

  ssh {
    name            = "devbox-${each.value}"
    hostname        = aws_network_interface.this[each.value].private_ip
    username        = var.ssh_username
    port            = 22
    port_forwarding = true
  }

  provisioner "local-exec" {
    command = "sdm admin users grant-temporary --until=2030-01-01T00:00:00+07:00 devbox-${each.value} ${each.value} --force"
  }
}
```

While this works, it requires the invoking user to have both `sdm`, be logged in, and be in an admin role.    

Ask:

- allow users to be members of multiple roles -- this would require no changes in the SDM provider
- add support for granting temporary access to the SDM provider

Thanks,
Nigel.

**Comment by netflash** [comment] 2021-05-05 00:02
I would back up the `temporary access` part as well.

**Comment by barywhyte** [comment] 2021-05-24 20:33
Hi, 

I am using strongDM terraform provider version `1.0.20` with terraform version `0.11.15`. I have the plugin downloaded and working fine with terraform version `0.11.15`

Here is my code:
```
terraform {
  required_version = "0.11.15"

provider "sdm" { 
    #source = "strongdm/sdm" 
    version = "v1.0.20"       
}

resource "sdm_resource" "dear_s" {
    postgres {
        name =  "name"
        hostname        = "hostname.net"
        database         = "db-name"
        username        = "username"
        password        = "password"
        port                 = 2342
    }
}

resource "sdm_resource" "dear_b" {
    postgres {
         name            =  "name"
        hostname     = "hostname-2.net"
        database      = "db-name-2"
        username     = "username-2"
        password     = "password-2"
        port              = 2342
    }
}

resource "sdm_resource" "gke_cluster" {
    google_gke {
        name                               =  "cluster-name"
        endpoint                         =  "10.23.10.8"
        certificate_authority      =  "${file(./.keys/gke_cert_auth.crt)}"
        service_account_key    =  "${file(./keys/gcp_account.json)}"
        
       
    }
}

```

`terraform init`
`terraform apply`

The first two resources were successfully created in strongDM UI but the last time failed to create and output the following error:
```
Error: Error applying plan:

1 error occurred:
        * sdm_resource.gke_cluster: cannot create Resource: error validating datasource: invalid operation: cannot validate ca cert: invalid cert block pem data
```
The strange thing is that I can do this successfully on strongDM UI with the same certificate authority credential.

What am I doing wrong here?

**Comment by 200sc** [comment] 2023-01-26 15:06
A user can be a part of multiple roles since around a year ago, hopefully resolving this issue.

@barywhyte This issue appears unrelated, if you are still encountering this please open a new issue with reproduction steps, in particular the content of the file causing problems (obfuscated as necessary).

**Closed by 200sc** 2023-01-26 15:06 UTC
